export const specialistDoctors = [
    "Allergist",
    "Anesthesiologist",
    "Cardiologist",
    "Dermatologist",
    "Endocrinologist",
    "Gastroenterologist",
    "General Surgeon",
    "Hematologist",
    "Infectious Disease Specialist",
    "Intensive Care Specialist",
    "Internal Medicine Specialist",
    "Neonatologist",
    "Nephrologist",
    "Neurologist",
    "Neurosurgeon",
    "Obstetrician",
    "Oncologist",
    "Ophthalmologist",
    "Orthopedic Surgeon",
    "Otolaryngologist",
    "Pediatrician",
    "Plastic Surgeon",
    "Podiatrist",
    "Psychiatrist",
    "Pulmonologist",
    "Radiologist",
    "Rheumatologist",
    "Urologist",
    "Vascular Surgeon",
    "Allergy and Immunology Specialist",
    "Anatomic Pathologist",
    "Andrologist",
    "Bariatric Surgeon",
    "Breast Surgeon",
    "Cardiac Electrophysiologist",
    "Cardiothoracic Surgeon",
    "Clinical Geneticist",
    "Colorectal Surgeon",
    "Critical Care Medicine Specialist",
    "Cytopathologist",
    "Dentist",
    "Developmental-Behavioral Pediatrician",
    "Emergency Medicine Specialist",
    "Family Physician",
    "Forensic Pathologist",
    "Gynecologist",
    "Hand Surgeon",
    "Hepatologist",
    "Hospitalist",
    "Immunologist",
    "Infectious Disease Physician",
    "Interventional Cardiologist",
    "Interventional Radiologist",
    "Maxillofacial Surgeon",
    "Medical Geneticist",
    "Microbiologist",
    "Molecular Geneticist",
    "Nuclear Medicine Specialist",
    "Occupational Medicine Specialist",
    "Ophthalmic Plastic Surgeon",
    "Oral and Maxillofacial Surgeon",
    "Orthodontist",
    "Orthopedic Oncologist",
    "Pain Management Specialist",
    "Pathologist",
    "Pediatric Cardiologist",
    "Pediatric Endocrinologist",
    "Pediatric Gastroenterologist",
    "Pediatric Hematologist-Oncologist",
    "Pediatric Infectious Disease Specialist",
    "Pediatric Nephrologist",
    "Pediatric Neurologist",
    "Pediatric Ophthalmologist",
    "Pediatric Orthopedic Surgeon",
    "Pediatric Otolaryngologist",
    "Pediatric Pulmonologist",
    "Pediatric Radiologist",
    "Pediatric Rheumatologist",
    "Pediatric Surgeon",
    "Pediatric Urologist",
    "Phlebologist",
    "Physical Medicine and Rehabilitation Specialist",
    "Plastic and Reconstructive Surgeon",
    "Podiatric Surgeon",
    "Prosthodontist",
    "Psychosomatic Medicine Specialist",
    "Sleep Medicine Specialist",
    "Sports Medicine Specialist",
    "Thoracic Surgeon",
    "Toxicologist",
    "Transplant Surgeon",
    "Trauma Surgeon",
    "Vascular and Interventional Radiologist",
    "Vascular Medicine Specialist",
    "Venereologist",
];

export const cities = ["Almaty", "Karaganda", "Shymkent", "Taraz", "Nur-Sultan", "Pavlodar", "Oskemen", "Semey", "Oral", "Aktobe", "Qostanay", "Kostanay", "Kyzylorda", "Petropavl", "Temirtau"]
